name: outfit_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  elliptic_text: ^1.0.0
  flutter_circular_text: "^0.3.1"
  circular_profile_avatar: ^2.0.0
  path_drawing: ^1.0.1

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  fonts:
    - family: bukhari
      fonts:
        - asset: police\Bukhari Script.ttf 
   
    - family: grandcru
      fonts:
        - asset: police\GrandCru-LightS.otf